import string
import time
import requests
import random
from datetime import date, datetime
import calendar

from enum import Enum

class s(Enum):
    punctuation = 1
    digits = 2
    ascii_letters = 3
    ascii_lowercase = 4
    ascii_uppercase = 5
    whitespace = 6

def save_token(message: str):
    path = "your/file/path/here.extension"
    with open(path, "w") as file:
        file.write(message)

def get_string(type, k=2):
    match type:
        case s.punctuation:
            return string.punctuation
        case s.digits:
            return string.digits
        case s.whitespace:
            return string.whitespace
        case s.ascii_letters:
            return string.ascii_letters
        case _:
            return "Type not found"

def token(key, length=128):
    return key + ''.join(list(random.choices(list(get_string(s.punctuation)), k=1))) + ''.join(random.choices(list(get_string(s.ascii_letters)), k=length))

class t(Enum):
    now = 1
    month = 2

def timestamp(type):
    match type:
        case t.now:
            return time.time_ns()
        case t.month:
            month = int(date.today().strftime("%m"))
            year = int(date.today().strftime("%Y"))
            lmd = int(calendar.monthrange(year, month)[1])
            return int(datetime(year, month, lmd, 23, 59, 59).timestamp())

def message(token, timestamp = timestamp(t.now), expired = timestamp(t.month)):
    pub_keys = f"yourpubkeyhere"
    return f"""\
Public Key = {pub_keys}
Token = {token}
Generated by Timestamp = {str(timestamp)} 
Expired by Timestamp = {str(expired)}
    """

message = message(token("yourkeyhere"))
save_token(message)
